### ISSUE TITLE
Noto Nastaliq Urdu: Wrong Nuqta and Tah placement in U+0768 ARABIC LETTER NOON WITH SMALL TAH and U+08C7 ARABIC LETTER LAM WITH SMALL ARABIC LETTER TAH ABOVE respectively

### ISSUE THREAD

**Issue by TheBluuDot** [notofonts/nastaliq#16]
### Font 
**NotoNastaliqUrdu-Regular.ttf** and **NotoNastaliqUrdu-Bold.ttf** 
Site: https://github.com/googlefonts/noto-fonts/tree/ad82c41a1b0277ec45081beb6abedba788598074/unhinted/ttf/NotoNastaliqUrdu Version: 3.003

### Issues

The Nuqta is being rendered at the top along with the Tah in the isolated form of U+0768 ARABIC LETTER NOON WITH SMALL TAH when it should be at the same position as in U+0646 ARABIC LETTER NOON. Furthermore, the Tah should be very slightly higher than the Nuqta in all forms.

Regular:

![image](https://user-images.githubusercontent.com/62665768/176775452-0db8a2dc-8f8d-4674-90f3-36c907c824f0.png)
Bold:

![image](https://user-images.githubusercontent.com/62665768/176775485-2e6bae9b-2b82-49da-88e7-7cb82c5d4c42.png)

This how a Punjabi centric Nastaliq font, [Roz Urdu Punjabi Nastaleeq](http://punjabiandpunjab.com/Font_Licence.html), renders it:

![image](https://user-images.githubusercontent.com/62665768/176775517-c0fd546a-bf80-40aa-a763-9d7728ab9668.png)

The Tah in U+08C7 ARABIC LETTER LAM WITH SMALL ARABIC LETTER TAH ABOVE should be exactly at the top of the danda of the lam as instructed by Unicode:

![image](https://user-images.githubusercontent.com/62665768/176775207-3ce81e4e-14bc-4796-8acd-d5da378ec0e7.png)

But Noto Nastaliq renders it like this in Regular:

![image](https://user-images.githubusercontent.com/62665768/176775307-88fc2018-9c78-4996-b439-7fb7e93ba7b5.png)

and Bold:

![image](https://user-images.githubusercontent.com/62665768/176775333-a34cf3f4-709b-47cd-bf74-5bb7076947e4.png)

Both Isolated and Final forms are affected.

**Comment by bgo-eiu** [comment]
These are good points - I have noticed the proportions of these characters stand out in Noto. Unfortunately the Roz font is not open source, so it cannot be used for many things.

**Comment by TheBluuDot** [comment]
>  Unfortunately the Roz font is not open source, so it cannot be used for many things.

Yeah and it's the only Nastaliq font that I could find which has support for U+0768. And even it does not support U+08C7.

**Comment by bgo-eiu** [comment]
Oddly, Roz does not use the style of hamza over ye typical of Urdu/Punjabi writing either. I'll try working on a PR for this since Noto is at least open source, but it might take a while as I've not modified a font before.
