### ISSUE TITLE
Noto Nastaleeq should support Arabic Presentation Forms

### ISSUE THREAD

**Issue by kulpreetchilana** [notofonts/nastaliq#2]
Consider the following Persian text I encountered online:

ویدئو ﻫﺎﯼ ﺗﻮپ

If I set the font to Noto Nastaleeq, I get this weird mixture of Naksh and Nastaleeq:

![screen shot 2017-04-21 at 2 04 21 pm](https://cloud.githubusercontent.com/assets/235441/25296156/b9e5d21a-269b-11e7-98c7-208d36a3929b.png)

In the string above, the second part uses Arabic Presentation Forms:

ﻫﺎﯼ ﺗﻮپ

I’m assuming Noto Nastaleeq does not support these, but but my system font does. Noto Nastaleeq should support these.

**Comment by simoncozens** [comment]
I don't think it makes sense to support these positional glyphs; as Khaled says, they shouldn't be used in input text. I would have done it if it were easy to do, but given that we're using ccmp decomposition in this font it would be a nightmare to implement.
