### ISSUE TITLE
Noto Nastaliq support for Balti Graf U+08C8

### ISSUE THREAD

**Issue by lateef-shaikh** [notofonts/nastaliq#3]
### Title 
 Noto Nastaliq support for Balti Graf U+08C8

### Font 
NotoNastaliqUrdu-Regular.ttf
NotoNastaliqUrdu-Bold.ttf

### Issue
This is actually a request not an issue. Recently Balti Graf U 08C8 is added in Unicode 14 version.
Can you please add this alphabet in Noto Nastaliq font? It's shape is similar to Arabic Gaaf.

**Comment by simoncozens** [comment]
Coming soon...

![shape](https://github.com/user-attachments/assets/b0698b2c-8d89-4998-a4cc-461b21cf701e)
