### ISSUE TITLE
Localized form of digits do not appear when used with a subtending mark

### ISSUE THREAD

**Issue by saadatm** [notofonts/nastaliq#47]
### Font 
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/nastaliq/releases/download/NotoNastaliqUrdu-v3.007/NotoNastaliqUrdu-v3.007.zip
Date: 2022-08-04

### Font Version
Version 3.007

### Issue
If we change the language of the text to (e.g.) Persian, and then use the digits with a subtending mark, then the localized forms of digits do not appear:
```
hb-view -o out-3.007-fa.png --language=fa NotoNastaliqUrdu-Regular-3.007.ttf "؀۴۶۷ ؁۴۶۷ ؂۴۶۷ ؃۴۶۷ ؄۴۶۷"
```
_Output from v3.007:_
![out-3 007-fa](https://user-images.githubusercontent.com/6615143/184382140-b96ed3c7-5fcb-4372-8e06-efb052ed40b6.png)

<hr>

As far as I can tell, this used to work correctly before v3.001 (example below uses v2.001):
```
hb-view -o out-2.001-fa.png --language=fa NotoNastaliqUrdu-Regular-2.001.ttf "؀۴۶۷ ؁۴۶۷ ؂۴۶۷ ؃۴۶۷ ؄۴۶۷"
```
_Output from v2.001:_
![out-2 001-fa](https://user-images.githubusercontent.com/6615143/184382804-888c50b5-f748-49a4-be0a-592ddad4f2f2.png)

**Comment by simoncozens** [comment]
Good catch!
