### ISSUE TITLE
Adding the letter ڭ to nastaliq

### ISSUE THREAD

**Issue by IlyasTarpan** [notofonts/nastaliq#48]
I am a native speaker of the Crimean Tatar language, who now uses Cyrillic and Latin, but before the 1940s, we used Arabic script, including Nastaliq, and sometimes there is a need to write in Arabic letters.
 And I faced the problem that in Urdu Noto Nastalik there is no letter ڭ, which is obligatory for the Crimean Tatar language.
 By the way, this letter is also found in Ottoman, Uighur, Kazakh, Uzbek and other Turkic languages ​​that use nastalik.
 
I would like this letter to be added to the Urdu Noto Nastalik font.
I'm not a programmer, and not a calligrapher, but if you need non-qualified help, I'm ready to help.
The letter should look something like this:
![Снимок экрана (1454)](https://user-images.githubusercontent.com/113206717/189424363-0eaeb99c-787d-46c7-a3e7-ced272b2716a.png)
![Снимок экрана (1462)](https://user-images.githubusercontent.com/113206717/189424409-2c80de79-4696-4574-a25f-e133fd6fbdab.png)
![Снимок экрана (1463)](https://user-images.githubusercontent.com/113206717/189424413-f20dd592-e22d-459a-9300-b99a748ad1b0.png)
![Снимок экрана (1464)](https://user-images.githubusercontent.com/113206717/189424414-4eedf28b-86e5-4b39-ac6f-beaf50745030.png)
![Снимок экрана (1465)](https://user-images.githubusercontent.com/113206717/189424416-fd06f1bd-aafa-4e80-b096-1898ea7c31f8.png)

**Comment by simoncozens** [comment]
Hello (again!) Ilyas! I've added the glyph U+06AD to Noto Nastaliq Urdu, like so:
![shape](https://user-images.githubusercontent.com/106728/192884345-dca17ea0-b8b6-4b80-a5e5-556945717b6f.png)

Development builds are available [here](https://notofonts.github.io/nastaliq/), the fixed version will appear on notofonts.github.io when there is a new release, and on fonts.google.com about a month after that.
