### ISSUE TITLE
Adjust the Arabic Thousands Separator (U+066C) to follow the design and position as English

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/nastaliq#49]
Hello. Thank you for providing us with great fonts.
I’d like to report what a native Urdu speaker hopes to have updated in Noto Nastaliq Urdu.

It applies to all Noto Nastaliq Urdu fonts:
[https://github.com/notofonts/nastaliq/releases/download/NotoNastaliqUrdu-v3.007/NotoNastaliqUrdu-v3.007.zip](url)

It is hope for the character form for Arabic Thousands Separator (U+066C) to stay as it is, and lower to the baseline, similar to the English comma.
By the way, Noto Naskh Arabic has the design this way.
[https://github.com/notofonts/arabic/releases/download/NotoNaskhArabic-v2.016/NotoNaskhArabic-v2.016.zip](url)

Please find below the links of a few pages where you can find some examples:
https://akhbar-e-jehan.com/detail/42535/executive-director-of-commission-renowned-bureaucrat-and-former-ambassador-dr-muhammad-nafees-zakaria
![image](https://github.com/notofonts/nastaliq/assets/122098208/72963520-d408-4a87-ad8f-f5beb202f89a)

https://akhbar-e-jehan.com/detail/42618/referendum-for-indigenous-parliamentary-rights-in-australia
![image](https://github.com/notofonts/nastaliq/assets/122098208/9029a808-96b2-4341-9ce0-dbb7aff86041)

https://www.express.pk/story/761623/?__cf_chl_tk=y3PGyKn4m2nbjYD4wGJOkif.fcS0SiL3vDo1N1CSFfY-1682502157-0-gaNycGzNEjs
![image](https://github.com/notofonts/nastaliq/assets/122098208/f950925c-6ae9-4665-a181-fad7cd324481)

https://akhbar-e-jehan.com/detail/42764/why-fifteen-minute-cities-are-becoming-popular-in-the-world
![image](https://github.com/notofonts/nastaliq/assets/122098208/0d25cdb9-74a6-40b7-a5ed-aaad073ab3c3)

Thank you for taking in this request into consideration.

**Comment by simoncozens** [comment]
I'm not convinced by this. Some Arabic fonts have U+066C above the baseline, and some on the baseline (and some have it backwards and some have it forwards):

Amiri:
![shape](https://github.com/notofonts/nastaliq/assets/106728/36f7233a-2e19-4eda-bbfa-04d1c5f606ea)
Scheherazade:
![shape](https://github.com/notofonts/nastaliq/assets/106728/d20ef5fb-2eec-44b9-9806-ce17fdaf4ab8)

Adobe Arabic:
![shape](https://github.com/notofonts/nastaliq/assets/106728/2ad37a71-525a-4f57-87f2-5f52bf9f110c)
Al Bayan:
![shape](https://github.com/notofonts/nastaliq/assets/106728/73c56974-3f8e-4d13-a0d9-4a308826334a)

I think I want to understand the differences first.

**Comment by simoncozens** [comment]
(There's an outline bug in the positioning of ۴ above the baseline in AlBayan; the things you discover...)

**Comment by YusukeShirakihara** [comment]
Thank you for looking into this matter. We agree there are different ways to design these punctuations.
We will also do some research and ask some native friends about this.
If we get information about strongly suggesting a specific style, I will make another post.
It would also be wonderful if several styles can be selected in one font.
