### ISSUE TITLE
Issue with Arabic sign sanah in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by Etewilak** [notofonts/nastaliq#5]
In Noto Nastaliq Urdu, if the Arabic sign sanah (U+0601) is encoded first before the number, the subtending feature does not work. If it is encoded after the number, the subtending feature works.
With Arabic sign sanah encoded after the digits:
![image](https://user-images.githubusercontent.com/55674356/152509716-65535532-ad1f-4627-9bc9-4ad1f9fb5bae.png)
With Arabic sign sanah encoded before the digits:
![image](https://user-images.githubusercontent.com/55674356/152509769-7c23b341-063f-4b59-a0e5-7262b1cb4c19.png)
For comparison, in Awami Nastaliq, the Arabic sign sanah must be encoded first before the digits. For example:
![image](https://user-images.githubusercontent.com/55674356/152509897-721f63de-45b7-401e-a620-9d2114934830.png)

**Comment by simoncozens** [comment]
I'm fairly sure this is fixed now. Please reopen if not:

```
$ shape fonts/NotoNastaliqUrdu/hinted/ttf/NotoNastaliqUrdu-Regular.ttf 'ابگ ؁۱۲۳۴'
[FourUrdu.small=4@1701,337+0|ThreeArabic.small=4@1294,337+0|TwoArabic.small=4@888,337+0|OneArabic.small=4@480,337+0|Sanah.alt4=4+2250|space=3+132|GafFin=2+957|OneDotBelowNS=1@73,-101+0|sp1=1+0|BehxIni=1@0,64+297|AlefSep=0+330]
```
![shape](https://github.com/notofonts/nastaliq/assets/106728/08afdf9b-6769-4309-99b3-15e337c9b9db)
