### ISSUE TITLE
Provide a dedicated font for Kashmiri Language

### ISSUE THREAD

**Issue by Iflaq12** [notofonts/nastaliq#52]
**Is your feature request related to a problem? Please describe.**
Kashmiri Language lacks support in terms of proper dedicated fornt for the langauage in digital settings. Though some fonts are available but there are instances of errors in the fonts. Most of the fonts have been developed for other languages and have been extened for Kashmiri language. I tried to write a document in Kashmiri and installed Noto Nastaliq Urdu but it seemed to render some characters in non Kashmiri format by default. As such people have to pay for properitary software even for small document typing.  

**Describe the solution you'd like**
If we have a dedicated font eg **Noto Nastaliq Kashmiri** it would be a default font for proper rendering of characters and serve as a bottomline. A dedicated font will make the writing more consise without errors as there are fonts supporting kashmiri but not properly.

**Additional context**
There are other fonts that support Kashmiri but they are breaking.

**Comment by simoncozens** [comment]
To be honest, I think it's unlikely that we'll do this; but if you give me more information about which characters are not working correctly, I'll do my best to ensure that the font works when the application language is set to Kashmiri.

**Comment by r12a** [comment]
In case it's useful, the following is a note from the beginning of my notes on Kashmiri at https://r12a.github.io/scripts/arab/ks.html

> Fonts: There are few nastaliq fonts around, and only a few of those support Kashmiri. This page uses a webfont of the [latest Noto Nastaliq Urdu font](https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoNastaliqUrdu) (v3.002). It has only very recently been adapted to support Kashmiri. Note that the language of the text needs to be set to 'ks' for the correct shapes to be applied. (At the time of writing, a macOS bug appears to prevent use of the latest version of the font when installed on your system – only the pre-installed version is available, but the webfont should work. And note also that Safari web browser, by policy, will only use pre-installed fonts. The latest version of the font works fine, however, when installed on Windows.) An alternative is to use SIL's [Awami Nastaliq](https://software.sil.org/awami/) font, but this is a Graphite font and so only works fully in the Firefox web browser, and font settings are needed to produce the rounded hamza diacritics, rather than the s-shaped ones in the Awami font.

**Comment by Iflaq12** [comment]
> To be honest, I think it's unlikely that we'll do this; but if you give me more information about which characters are not working correctly, I'll do my best to ensure that the font works when the application language is set to Kashmiri.

The hamza  "ٔ" in the Kashmiri has a different apperance than what is rendered in Microsoft while using this font. It seems to show up urdu hamza.

**Comment by Iflaq12** [comment]
> e are few nastaliq fonts around, and only a few

How do we set langage to ks when we are using this font in Microsoft.

**Comment by saadatm** [comment]
> How do we set langage to ks when we are using this font in Microsoft.

In Microsoft Word, the document language changes to whichever keyboard layout you are currently using (I personally find this UX very confusing for multilingual documents).

A better solution is to set the preferred authoring language of each new Word document to Kashmiri by following the steps on [this page](https://support.microsoft.com/en-us/office/add-an-editing-or-authoring-language-or-set-language-preferences-in-office-663d9d94-ca99-4a0d-973e-7c4a6b8a827d) (you'll have to expand the _Set the preferred display or authoring language_ section to see the instructions).

Yet another solution (which is great for multilingual documents) is to highlight the desired chunk of text, click on the language being displayed in the bottom toolbar, and select the desired language from the pop-up that appears.

**Comment by simoncozens** [comment]
I think this font supports Kashmiri as well as we can get it (and I haven't heard any issues about Kashmiri support); we're not likely to provide a dedicated font for it (although you can create your own with pyftfeaturefreezer if you want to); it is hard to set text language to Kashmiri in user applications, but that's not something we can do anything about in terms of this font; and so I think there's nothing left to do in this issue.
