### ISSUE TITLE
Support for major Pakistani languages

### ISSUE THREAD

**Issue by crackalamoo** [notofonts/nastaliq#53]
The Noto Nastaliq Urdu font has been incredibly successful, and is even a [system font on iOS and OS X](https://developer.apple.com/fonts/system-fonts/). Given this ubiquity, especially as some use this font as the primary Arabic-script font on their devices, it is important to support the most common languages that users encounter on the web.

Currently, in [Balochi](https://en.wikipedia.org/wiki/Balochi_language) and [Sindhi](https://en.wikipedia.org/wiki/Sindhi_language) among other languages, there is poor rendering for certain letters unique to these languages causing them to appear disjointed from the rest of the word.

Since Noto Nastaliq Urdu is an Urdu font, one could argue that these extra letters are not necessary: languages that use these letters can simply use a different font in which they are supported. However, since the font is also increasingly a _system_ font in addition to a CSS one for Urdu-language text, these issues can be disruptive for users accessing the web. Many websites and native apps use the default system font making it difficult to read these texts.

Therefore, it would greatly enhance the user experience if this font had letters in other languages, especially Pakistani ones. The font already supports certain non-Urdu letters such as ٻ in Sindhi; many others such as ݔ in Balochi can be designed simply by adding dots to existing letter forms.

Here are some screenshots that demonstrate the font issues:

<img width="787" alt="Screenshot 2023-08-13 at 15 05 30" src="https://github.com/notofonts/nastaliq/assets/37599247/1823db4c-597c-469b-ab41-2f4e4fd25a68">
<img width="694" alt="Screenshot 2023-08-13 at 15 05 53" src="https://github.com/notofonts/nastaliq/assets/37599247/8cafe130-5c72-4600-a56a-0036d7f1c270">
<img width="328" alt="Screenshot 2023-08-13 at 15 06 20" src="https://github.com/notofonts/nastaliq/assets/37599247/70c507da-e311-4ddc-8a9a-de8a51de0063">

**Comment by simoncozens** [comment]
Some of these letters are already supported, so I think you have an old version of the font installed:

![shape](https://github.com/notofonts/nastaliq/assets/106728/0de6fc64-632c-423a-ac67-56e6f4562d20)

But others (ڕ, ڪ, ڵ) still need to be added. I'll add these.

**Comment by simoncozens** [comment]
3.007 has ێ and ݔ. If you can't see them, it may be that you have an older version installed as a system font and this is overriding your user-installed version.

**Comment by sal-ammoniac** [comment]
> 3.007 has ێ and ݔ. If you can't see them, it may be that you have an older version installed as a system font and this is overriding your user-installed version.

Thanks

**Comment by khaledhosny** [comment]
I was asked to support ڪ in a Nastaliq font once, but I couldn’t find any precedence of this letter shape in Nastaliq (it is a Naskh forms that has its root in Kufi, but it seems to have never been used in Nastaliq), and Sindhi, unlike most Pakistani languages, seems to be always written in Naskh and never Nastaliq.

**Comment by bgo-eiu** [comment]
@khaledhosny I asked a Sindhi speaking friend recently what Sindhi writers who prefer Nastaliq choose to do about this, and apparently it is this.

(For what its worth, I think this looks terrible. I don’t know if they are holding out for a font with a better option or if they actually prefer it like this.)

![IMG_20230902_092052](https://github.com/notofonts/nastaliq/assets/100172442/18a22955-23d2-4fc9-8491-90dceed64251)

**Comment by simoncozens** [comment]
That's horrible. But in which case, we're all done here. (Or will be at the next release.)

**Comment by moyogo** [comment]
@bgo-eiu What do they do in handwriting?
