### ISSUE TITLE
Some part of glyphs disappearing on Microsoft Word 

### ISSUE THREAD

**Issue by YusukeShirakihara** [notofonts/nastaliq#54]
Hello. Thank you for providing us with great fonts.
I’d like to report a request from native Urdu speakers to fix Noto Nastaliq Urdu.

It applies to Noto Nastaliq Urdu fonts v3.007:
https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoNastaliqUrdu/hinted/ttf/NotoNastaliqUrdu-Bold.ttf
https://cdn.jsdelivr.net/gh/notofonts/notofonts.github.io/fonts/NotoNastaliqUrdu/hinted/ttf/NotoNastaliqUrdu-Regular.ttf

**Sample**
بچے اپنے فیصلے چاہتے پہلے 
U+0628,0686,06D2
U+0627,067E,0646,06D2
U+0641,06CC,0635,0644,06D2
U+0686,0627,06C1,062A,06D2
U+067E,06C1,0644,06D2

Although these strings can be correctly displayed on Harfbuzz, some part of glyphs disappeared on **_Microsoft Word 2019_**. 
### NotoNastaliqUrdu-Regular.ttf
hb-view (harfbuzz 2.7.4, Ubuntu 22.04.3 LTS)
![image](https://github.com/notofonts/nastaliq/assets/122098208/0a960dc6-0270-4341-85ab-3107a67c006a)
**_Microsoft Word 2019_** (Windows 11 Pro 22H2)
![image](https://github.com/notofonts/nastaliq/assets/122098208/6e75b2ef-253f-4151-8731-0ab75255db64)
### NotoNastaliqUrdu-Bold.ttf
hb-view (harfbuzz 2.7.4, Ubuntu 22.04.3 LTS)
![image](https://github.com/notofonts/nastaliq/assets/122098208/ffb90814-be0b-4b21-beec-e1c5f34da19b)
**_Microsoft Word 2019_** (Windows 11 Pro 22H2)
![image](https://github.com/notofonts/nastaliq/assets/122098208/cc1abf4f-cd9a-450a-82cb-a5f91fb0e33a)
Thank you for taking this request into consideration.

**Comment by YusukeShirakihara** [comment]
FYI
https://github.com/microsoft/WindowsAppSDK/issues/3830

**Comment by adarshdevapps** [comment]
FYI, 
For anyone looking for quick workaround,
I was able to to see the characters rendered properly on Libre Office Writer 7.6.

**Comment by simoncozens** [comment]
Thanks for filing this with Microsoft; it is a Microsoft rendering bug, rather than a font bug, so we'll see what they say.
