### ISSUE TITLE
Add arabic letter ڮ (U+06AE ARABIC LETTER KAF WITH THREE DOTS BELOW)

### ISSUE THREAD

**Issue by jibrant3ch** [notofonts/nastaliq#55]
Hello. I'm from Indonesia
Anyway, I want to add ARABIC LETTER KAF WITH THREE DOTS BELOW because this letter ݢ (U+0762 ARABIC LETTER KEHEH WITH DOT ABOVE) is available in this font. I want this for writing Pegon Arabic. ݢ is only for Jawi

**Comment by simoncozens** [comment]
Hi! This was recently added (see #10) and will be available in the next release of Noto Nastaliq Urdu.

**Comment by jibrant3ch** [comment]
Okay. Thank you and could you please tell me if the font getting updated
    Pada Senin, 28 Agustus 2023 pukul 23.19.14 WIB, Simon Cozens ***@***.***> menulis:  
 
 


Hi! This was recently added (see #10) and will be available in the next release of Noto Nastaliq Urdu.
