### ISSUE TITLE
Dot collisions after v3.008

### ISSUE THREAD

**Issue by saadatm** [notofonts/nastaliq#57]
### Font
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/nastaliq/releases/tag/NotoNastaliqUrdu-v3.008
Date: 2023-09-27

### Font Version
3.008

### Issue
I noticed some dot collisions in v3.008 that were not present in v3.007. Some examples (and a comparison screenshot) below. (Please note that this list isn't exhaustive; these are just some collisions that I found on a single post on my blog.)

```
چتا
دیتا
کتنا
بیٹھا
چند
ئز
پیش
ختو
نتو
فٹو
ہیں
```

### Screenshot
![collisions-3 008](https://github.com/notofonts/nastaliq/assets/6615143/c3f4b5c8-1191-4329-a3a9-f142a7b18991)

**Comment by simoncozens** [comment]
OK, this is weird; the shaping code has not changed at all between 3.007 and 3.008. I will investigate but it's obvious something has gone very very wrong with the build.

**Comment by simoncozens** [comment]
73a7fef seems to have removed all the shaping code!

**Comment by simoncozens** [comment]
I've put it all back. Should be fixed now. I'll do a new release.
