### ISSUE TITLE
Shape of ک in some sequences has changed in v3.008

### ISSUE THREAD

**Issue by saadatm** [notofonts/nastaliq#58]
### Font
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/nastaliq/releases/tag/NotoNastaliqUrdu-v3.008
Date: 2023-09-27

### Font Version
3.008

### Issue
In v3.007 and older, the letter ک used a nice variant in some sequences.
In v3.008, that variant does not appear anymore.

Some examples are below.

Note that the shape in v3.008 isn't _wrong_. It's just that that ک variant in v3.007 and older added a bit of character to the overall design, and I would love to have it back. 😊

### Screenshot
![kaf-3 008](https://github.com/notofonts/nastaliq/assets/6615143/ebb916b5-4159-4380-b31d-86c41516a141)

These are the lettergroups in the above screenshot:
```
کھے
گھے
لکھے
یکھے
پنکھے
تیکھے
سیکھے
لنگھے
```

**Comment by simoncozens** [comment]
Another victim of the bad patch; fixed it.
