### ISSUE TITLE
Kerning issues in sequences ending in U+06D2 ARABIC LETTER YEH BARREE (ے) in v3.008

### ISSUE THREAD

**Issue by saadatm** [notofonts/nastaliq#59]
### Font
NotoNastaliqUrdu-Regular.ttf

### Where the font came from, and when
Site: https://github.com/notofonts/nastaliq/releases/tag/NotoNastaliqUrdu-v3.008
Date: 2023-09-27

### Font Version
3.008

### Issue
In v3.008, many sequences that end with U+06D2 ARABIC LETTER YEH BARREE (ے) are not being kerned correctly. Some examples are below; a lot others may be seen on [this page](https://saadatm.github.io/test-pages/ligatures-ending-in-yeh-barree/index.html) which lists Urdu sequences ending in ے.
```
ٹھونکنے
سامنے
کے نیچے
کے لیے
کے تنے
اپنے
ٹھونکے گئے
دیتے
ڈالنے
```
### Screenshot
![kern-yay-3 008](https://github.com/notofonts/nastaliq/assets/6615143/dfdb2d75-e2df-4191-8b01-052ac1f1dac9)

**Comment by simoncozens** [comment]
Another victim of my surprise decision to rip out all the shaping rules. I mean, they're insane, but we should definitely keep them. Fixed now.
