### ISSUE TITLE
dot collision, lam followed by peh

### ISSUE THREAD

**Issue by visionario2** [notofonts/nastaliq#64]
NotoNastaliqUrdu-Regular.otf

When lam is followed by peh, even with a space between, the letters collide, for example with these two words:
مسائل پیدا 
Tested in Word and Indesign 2024. 
![nastaliq lam peh](https://github.com/notofonts/nastaliq/assets/48595080/9386558a-8bd8-4bdc-b440-246a5b24981b)

**Comment by visionario2** [comment]
Actually, I don't think it's the preceeding letter at issue, but rather the dots of the peh being too far to the right.

**Comment by simoncozens** [comment]
Yes, the peh dots are shifted right because of the following yeh. If you have PNDA instead of PIDA then it doesn't collide. This'll be a tricky one...
