### ISSUE TITLE
Missing ligatures

### ISSUE THREAD

**Issue by MAZ06** [notofonts/nastaliq#66]
### Font 
NotoNastaliqUrdu[wght].ttf

### Where the font came from, and when
https://github.com/notofonts/nastaliq/releases/tag/NotoNastaliqUrdu-v3.009

### Font Version
NotoNastaliqUrdu-v3.009

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
Noto Nastaliq is missing several ligatures. There may be more than this but I've found these to be missing:
﷏ﷰﷱﷳﷵﷶﷷﷸﷹ﷾﷿

### Character data
﷏ U+FDCF
ﷰ  U+FDF0 
ﷱ U+FDF1
ﷳ U+FDF3
ﷵ U+FDF5
ﷶ U+FDF6
ﷷ U+FDF7
ﷸ U+FDF8
ﷹ U+FDF9
﷾ U+FDFE
﷿ U+FDFF

**Comment by MAZ06** [comment]
These too:
﵀﵁﵂﵃﵄﵅﵆﵇﵈﵉﵊﵋﵌﵍﵎﵏

**Comment by simoncozens** [comment]
It's a goal for Noto fonts to have complete coverage of Unicode between them; it's not necessarily a goal for *all* Noto fonts in a script to have complete coverage of that script, although it is the ideal. So I'd like this to happen one day, but it's not a priority.
