### ISSUE TITLE
Overlap with v4

### ISSUE THREAD

**Issue by MAZ06** [notofonts/nastaliq#68]
### Font 
NotoNastaliqUrdu[wght].ttf

### Where the font came from, and when
https://github.com/notofonts/nastaliq/releases

### Font Version
4.000

### OS name and version
Windows 11

### Issue
Just tried out the new v4 font and immediately noticed some overlap which I know wasn't in v3. See screenshot below.

### Character data
ترین

### Screenshot
![image](https://github.com/user-attachments/assets/b0ebdeaa-0751-413f-a0dc-7cec0b4b3e3d)

**Comment by simoncozens** [comment]
Ah, bad anchor placement in the bold. Can fix that.
